version: '3.7'
services:
  db:
    image: postgres:12-alpine
    ports:
      - 5434:5432
    env_file:
      .env
  web:
    build:
      context: sako
      dockerfile: Dockerfile.local
    #  command: python3 manage.py runserver
    volumes:
      - ./sako/:/app
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - .env


