# Generated by Django 3.1.5 on 2022-03-13 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_bestseller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='descrtiption',
            field=models.TextField(),
        ),
    ]
